FROM apache/kafka:4.0.0

# Copy JAAS config for SASL/PLAIN authentication
COPY jaas.conf /etc/kafka/jaas.conf

ENV KAFKA_NODE_ID=1
ENV KAFKA_PROCESS_ROLES=broker,controller
ENV KAFKA_LISTENERS=PLAINTEXT://0.0.0.0:9092,CONTROLLER://0.0.0.0:9093
ENV KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
ENV KAFKA_CONTROLLER_LISTENER_NAMES=CONTROLLER
ENV KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
ENV KAFKA_CONTROLLER_QUORUM_VOTERS=1@kafka:9093
ENV KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=1
ENV KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR=1
ENV KAFKA_TRANSACTION_STATE_LOG_MIN_ISR=1
ENV KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS=0
ENV KAFKA_NUM_PARTITIONS=3

ENV KAFKA_SASL_ENABLED_MECHANISMS=PLAIN
ENV KAFKA_SASL_MECHANISM_INTER_BROKER_PROTOCOL=PLAIN

EXPOSE 9092 9093

# Set environment variable to enable JAAS
ENV KAFKA_OPTS="-Djava.security.auth.login.config=/etc/kafka/jaas.conf"
